
version: "3"
services:
  web:
    build: .
    ports:
      - "5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    ports:
     - "5432"
